### PR TITLE
Adds Row/Column removal feature

### PR DESCRIPTION
**Pull request by christoph-kluge**
Kapture 2020-12-11 at 15 55 42

I've added a modified version of #48 which fixes couple of issues and adds more usability features:

* removed couple of error-messages during development
* remove bugs while adding/removing rows/cols - which where causing that we had random insertions
* remove minus button if you're in the first/last row/col
* added little bit of coloring to see which colum/direction is affectect for addition/deletion

### CODE REVIEW

**Comment by robonetphy** [comment]
Hi @christoph-kluge,
Thanks for creating PR I will look into it.

**Review by joeydash — APPROVED** [review]

**Review by omegion — APPROVED** [review]

**Review by eddrichjanzzen — APPROVED** [review]

**Comment by dipiash** [comment]
Hello! What about merging this PR or publishing beta-tag?

**Comment by mmiedzianyy** [comment]
Hello,
Any news on the PR?
Is there a plan to merge this request any time soon?

**Comment by moazam1** [comment]
Please update us.

**Comment by robonetphy** [comment]
Sorry 🙏 For Late reply, 
Since this PR is not resolving all the underlined issues it's hard for us to merge this PR with the current version.
but we are planning to come up with our own solutions for this so, be tuned.

**Comment by alexisvisco** [comment]
@robonetphy So ridiculous and disappointing. 

Someone works hard to provide a solution to a problem which in my opinion must be by default in this addon and you are throwing all his work into the trash.

This PR was firstly made nearly 1 year ago. Just try to help the author of this PR instead of saying "I will rewrite all your stuff because it's not perfect"

OpenSource in 2021. Nice.

**Comment by neSpecc** [comment]
> @robonetphy So ridiculous and disappointing.
> 
> Someone works hard to provide a solution to a problem which in my opinion must be by default in this addon and you are throwing all his work into the trash.
> 
> This PR was firstly made nearly 1 year ago. Just try to help the author of this PR instead of saying "I will rewrite all your stuff because it's not perfect"
> 
> Open Source in 2021. Nice.

The problem not in the PR, but in the plugin itself. The current implementation and UI are not stable and maintainable. We will create the new ones from scratch using existing experience. Will be released this spring. 

And of course, we thank all the people who help us to resolve problems. We are using these ideas in the design of future implementation.

**Comment by joeydash** [comment]
Please merge the pull request or create the feature from scratch we need this feature @neSpecc 
Is there any alternative of editorjs ? @simpleauthority

**Comment by simpleauthority** [comment]
> Is there any alternative of editorjs ? @simpleauthority

Unfortunately not, @joeydash. We are at their mercy. Despite this, editor-js is still the best, free, OSS editor around. However, I will not be using it as a result of this poor management. Sad. 

The next best is probably CKEditor. Version 4 is free, and version 5 is free for OSS.

**Comment by richstandbrook** [comment]
> Is there any alternative of editorjs ? @simpleauthority

It depends what you need as an alternative, I haven't found anything quite like editorjs, but Quill, Trix and ProseMirror are all really good well structured wysiwyg editors.

We need to keep in mind that this is an opensource project offered for free, the developers are not under an obligation to merge in anything they don't want to. You are liberty to fork the code and integrate any changes you want. That said, it would be nice to think that community contributions are carefuly considered and not just dismissed out of hand. Also unless they really are developing the feature imenently it would seem prudent to merge in and then replace the feature with thier own once it's done?

**Comment by simpleauthority** [comment]
> it would seem prudent to merge in and then replace the feature with thier own once it's done?

That's all I want. This has been an issue for a very long time.

**Comment by calumk** [comment]
+1 Adding my disappointment here that this cant be fixed, even if it will later be replaced.....

**Comment by neSpecc** [comment]
Thanks to all.

The new Table tool is here. You'll be able to remove all those extra columns at last.

**Pull request closed without merging**
