### PR TITLE
Table print view

### PR DESCRIPTION
**Pull request by hsanshine**
**This Pull Request is for: (delete those that don't apply)**
* Adding styles for the table in print media 

**Why this PR was needed**
* When the table's window is printed, it includes the `+` buttons and row extensions. Hiding these on print media improves the view. [Check images below]

**What this PR does**
- Adds post CSS styles to hide the `+` buttons
- Adds post CSS styles to hide row extensions on the left side
- Adds a left border

**Outcomes of merging this PR**
 - Improves the look of table on 
 
 * `BEFORE (on print media)`
Screen Shot 2022-07-06 at 6 19 05 PM
*  `AFTER (on print media)`
Screen Shot 2022-07-06 at 5 48 26 PM

### CODE REVIEW

**Comment by hsanshine** [comment]
* I will reopen the pull request again to indicate the issues it solves

**Review by neSpecc — APPROVED** [review]
Please, update a patch version

**Comment by hsanshine** [comment]
> Please, update a patch version

Patch has been updated in package.json from 2.0.2 to 2.0.3

**Comment by hsanshine** [comment]
> 
Hello
Patch has been updated from 2.0.3 to 2.0.4 after merging master, thanks!

**Comment by neSpecc** [comment]
Thanks

**Comment by hsanshine** [comment]
Pleasure is all mine!!!

**Pull request merged**
